on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "!*"

name: CI

env:
  CI: 1
  WORKSPACE: ${{ github.workspace }}

jobs:
  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    env:
      LINT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREFIX_FILTER: |
            configs/
            src/
            tests/
          SUFFIX_FILTER: .php
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
        if: env.GIT_DIFF
      - name: Cache composer modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
        if: env.GIT_DIFF
      - name: Prepare setting
        run: composer prepare
        if: env.GIT_DIFF
      - name: Check code style
        run: composer phpcs
        if: env.GIT_DIFF
      - uses: 8398a7/action-slack@v2
        with:
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    env:
      LINT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREFIX_FILTER: |
            configs/
            src/
            tests/
          SUFFIX_FILTER: .php
          SEPARATOR: ','
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
        if: env.GIT_DIFF
      - name: Cache composer modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
        if: env.GIT_DIFF
      - name: Prepare setting
        run: composer prepare
        if: env.GIT_DIFF
      - name: Check code style
        run: composer phpmd
        if: env.GIT_DIFF
      - uses: 8398a7/action-slack@v2
        with:
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  phpunit:
    name: PHPUnit
    needs: [phpcs, phpmd]
    runs-on: ubuntu-16.04
    services:
      mysql:
        image: mysql
        ports:
          - 3306
    strategy:
      matrix:
        php: ['7.3', '5.6']
        include:
          - php: '7.3'
            SEND_CODECOV: 1
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-git-comment-action@v1
      - uses: technote-space/get-diff-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREFIX_FILTER: |
            configs/
            src/
            tests/
          SUFFIX_FILTER: .php
          FILES: composer.lock
        if: "! contains(env.COMMIT_MESSAGE, '[skip ci]') && ! contains(env.COMMIT_MESSAGE, '[ci skip]')"
      - name: Switch PHP version
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: sudo ln -sf "/usr/bin/php$PHP_VERSION" /etc/alternatives/php
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Cache composer modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Prepare setting
        run: composer prepare
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Run tests
        run: composer phpunit
        if: env.GIT_DIFF || github.event_name == 'push'
      - name: Codecov
        run: |
          if [ -n "$CODECOV_TOKEN" ]; then
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f $COVERAGE_FILE
          fi
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          COVERAGE_FILE: ./coverage/clover.xml
        if: matrix.SEND_CODECOV == 1 && (env.GIT_DIFF || github.event_name == 'push')
      - uses: 8398a7/action-slack@v2
        with:
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

  slack:
    name: Slack
    needs: [phpunit]
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v2
        with:
          status: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
